### ISSUE TITLE
Admin interface

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-group-reviews#10]
### Acceptance criteria

- AC 1 - "The admin site must have a admin login for protection."
- AC 2 - "The admin interface must be properly styled to accomodate user experiance."

### Tasks

- [ ] Create the login credentials
- [ ] Create the model
- [ ] Create the view
- [ ] Create the url pattern
- [ ] Create the template
