### ISSUE TITLE
Register and create a profile

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-group-reviews#3]
### Acceptance criteria

- AC 1 - "To register and account a unique username, a password and a valid email address must be provided."
- AC 2 - "I can provide my age, gender, movie preferences in plain text and a short description about myself."

### Tasks

- [ ] Create the model
- [ ] Create the view
- [ ] Create the url pattern
- [ ] Create the template
- [ ] Create the form
- [ ] Add form control
