### ISSUE TITLE
Display and filter movies

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-group-reviews#4]
### Acceptance criteria

- AC 1 - "I can click on a navigation bar element and see all movies"
- AC 2 - "I can filter the movies list by various filters"
- AC 3 - "I can click on a movie to get detailed informations"

### Tasks

- [ ] Create the model
- [ ] Create the view
- [ ] Create the url pattern
- [ ] Create the template
- [ ] Create the filters
