### ISSUE TITLE
Create a group

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-group-reviews#5]
### Acceptance criteria

- AC 1 - "I can click on a navbar element to start the process."
- AC 2 - "I can select a unique name for my group."
- AC 3 - "I will be the super user of this group."
- AC 4 - "I can accept and decline users that want to join my group."

### Tasks

- [ ] Create the model
- [ ] Create the view
- [ ] Create the url pattern
- [ ] Create the template
- [ ] Create the form
