### ISSUE TITLE
Display and filter actors

### ISSUE THREAD

**Issue by NixTS** [NixTS/movie-group-reviews#8]
### Acceptance criteria

- AC 1 - "On the actors page i can clearly see their pircture and name."
- AC 2 - "I can filter actors by various filters."
- AC 3 - "I can click on their profile picture and see more informations about them."

### Tasks

- [ ] Create the model
- [ ] Create the view
- [ ] Create the url pattern
- [ ] Create the template
- [ ] Create the form
- [ ] Create the filters
